CREATE TABLE T_TESTE_DDL (
    CD_TESTE NUMBER(3) NOT NULL,
    NM_TESTE VARCHAR2(30) NOT NULL,
    DS_TESTE VARCHAR2(60) NULL,
    DT_TESTE DATE         NULL
);

ALTER TABLE T_TESTE_DDL ADD CONSTRAINT PK_TESTE_DDL PRIMARY KEY (CD_TESTE);

ALTER TABLE T_TESTE_DDL ADD CONSTRAINT UN_TESTE_DDL_NOME UNIQUE (NM_TESTE);

ALTER TABLE T_TESTE_DDL ADD DS_EMAIL VARCHAR2(80);

ALTER TABLE T_TESTE_DDL ADD (DS_OBS1 VARCHAR2(50) NOT NULL, DS_OBS2 VARCHAR2(50));

ALTER TABLE T_TESTE_DDL MODIFY DS_OBS1 VARCHAR(80);

ALTER TABLE T_TESTE_DDL MODIFY DS_TESTE NOT NULL;

ALTER TABLE T_TESTE_DDL MODIFY DT_TESTE DEFAULT SYSDATE;

ALTER TABLE T_TESTE_DDL MODIFY NM_TESTE NULL;

ALTER TABLE T_TESTE_DDL DROP COLUMN DS_OBS2;

ALTER TABLE T_TESTE_DDL DROP CONSTRAINT PK_TESTE_DDL;

ALTER TABLE T_TESTE_DDL MODIFY DT_TESTE DEFAULT NULL;

ALTER TABLE T_TESTE_DDL RENAME TO T_TESTE_DDL_NOVO;

ALTER TABLE T_TESTE_DDL_NOVO RENAME TO COLUMN DS_EMAIL TO DS_EMAIL_NOVO;






